language : shell

env:
  - CONDA_PYTHON=2.7
  - CONDA_PYTHON=3.5
  - CONDA_PYTHON=3.6
  - CONDA_PYTHON=3.7

os :
- windows

cache :
  directories:
    - /c/tools/miniconda3
    - $HOME/AppData/Local/Temp/chocolatey

install:
  # Set conda path info
  - MINICONDA_PATH=/c/tools/miniconda3;
  - MINICONDA_SUB_PATH=$MINICONDA_PATH/Scripts;

  # Install miniconda
  - if [[ -d $MINICONDA_SUB_PATH ]]; then
      echo "miniconda for Windows already installed";
    else
      echo "installing miniconda for windows";
      choco install -y miniconda3;
    fi;
  - export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$PATH";
  - choco install -y openssl.light;
  - hash -r;
  - python -V
  - conda info -a
  - conda config --set always_yes yes --set changeps1 no;
  - conda update -q conda;
  - if [[ ! -d "$MINICONDA_PATH/envs/test-environment" ]]; then
      conda create -n test-environment python=$CONDA_PYTHON
      conda activate test-environment
    else
      conda activate test-environment
      conda update --all
    fi
  - python -V
  - pip install -U keyring netaddr ntlm-auth psutil pywin32 winkerberos futures pyinstaller

script: 
  - python -m py_compile px.py
  - python px.py --help
  - cmd /c build.bat